### ISSUE TITLE
Lone witness Mc 7:24/26-28a

### ISSUE THREAD

**Issue by KWachtel** [cceh/ntg#106] opened 2019-04-02 07:28 UTC
At Mc 7:24/26-28a, witness 728 should be aligned with 3, its first potential ancestor within the same attestation.

**Comment by KWachtel** [comment] 2019-04-02 08:07
This is due to issue #97, 728 is an ambiguous witness.

**Comment by MarcelloPerathoner** [comment] 2019-04-23 16:30
duplicate of #97

**Closed by MarcelloPerathoner** 2019-04-23 16:30 UTC
